### ISSUE TITLE
mtproto connection problem

### ISSUE THREAD

**Issue by A2116** [HirbodBehnam/MTProtoProxyInstaller#25]
mtproto connect from ADSL but not from the 4G network

**Comment by DanialNikbin** [comment]
I'm facing the same problem. It's not working on mobile network at all.

**Comment by HirbodBehnam** [comment]
Iran blocks MTproto proxy on fly.
Not related to script issue as said in the issue template.

**Comment by HirbodBehnam** [comment]
I thought to myself that maybe I should change the title and pin this issue in order to allow people to discuss this issue in only one thread.

**Comment by sinascorpion** [comment]
Is there any way to hide packet connections?

**Comment by DanialNikbin** [comment]
How did they block? I thought because of random padding they are not able to block.

**Comment by FaridAghili** [comment]
Anything new?

**Comment by HirbodBehnam** [comment]
I did some work on how Iran blocks Fake TLS and I found some interesting things.
It looks like that Iran blocks certain browser fingerprints in order to block proxies. Possibly if there is a lot of requests using a old or maybe specific browser fingerprint, it enables [whitelister](https://geneva.cs.umd.edu/posts/iran-whitelister/) on server. 
Whitlelister blocks all of the HTTPS traffic that is from old browsers. I have an server that has whitelister on it. I tried connecting to a legit HTTPS server on it with Chrome 76 (witch is the browser that [Cloak](https://github.com/cbeuw/Cloak) mimics) and I couldn't connect to it; However Chrome 85 and 64, Firefox 80 and cURL 7.55.1 were completely fine. Probably only some old browser signatures are blocked. It's also good to note that Fake TLS and OpenVPN are not working.
This also could explain why a lot of uses have problems connecting with iOS devices because [this file](https://github.com/TelegramMessenger/Telegram-iOS/blob/master/submodules/MtProtoKit/Sources/MTTcpConnection.m) that is probably the one that have the fingerprints, is not updated in a while.

I don't think anything is possible from server side to defeat this, because client hello is important. Maybe _just maybe_ updating the Client Hello fingerprint regularly in clients helps users to bypass the whitelister. Also, another good (but more complex) approach is to randomly use a fingerprint. Also there is no need to say that using a real TLS connection will fix most of these problems.

**Comment by alty-ir** [comment]
Maybe a possible way is that host mtproxy in iran server and tunneling the income traffics of proxy server to another server in other nations like germany via openvpn or other solutions.

**Comment by FaridAghili** [comment]
@alty-ir 
There's a solution already, check [this](https://github.com/freejohn123/mtproto-tls-server) out.

**Comment by MoSi8160** [comment]
there is no way to use ?
