### ISSUE TITLE
combine quota and user limiter with official script

### ISSUE THREAD

**Issue by A2116** [HirbodBehnam/MTProtoProxyInstaller#29]
if you can combine quota and user limiter with official proxy script as you did for python proxy

**Comment by HirbodBehnam** [comment]
No it's not possible

**Comment by A2116** [comment]
I see you wrote port forwarder exactly for this work
is it not possible to integrate configuration and setting into the main proxy installer script like python proxy?

**Comment by HirbodBehnam** [comment]
I don't think the script must be here. If there was a script, it would have been in that project's files not here.
The reason that python proxy does support user management and limitations is because that it natively (without any external program) supports these limits and can be configured in `config.py` file.

**Comment by A2116** [comment]
yes I know that these are two separate project
but for easier usage, I suggest this combination
