### ISSUE TITLE
request

### ISSUE THREAD

**Issue by Angize** [HirbodBehnam/MTProtoProxyInstaller#32]
Added view of the amount of traffic consumed by each proxy.

thanks.

**Comment by HirbodBehnam** [comment]
This is so hard to implement. Because the script have to read the logs of the proxy, parse them and calculate it. Not only I don't really have any idea how to do it, I think this is not something that the script must do; This is an "Installer" script; Not a "Manager" script.
If you want to do it manually or write an app/script, you have to look at mtprotoproxy logs (`systemctl status mtprotoproxy`) to see how much users have consumed until now; Then move to yesterday logs, and subtract two values. The result is the consumed traffic in the day before.
