### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by FemalePresident** [HirbodBehnam/MTProtoProxyInstaller#34]
Hi,

I encountered a new problem, the error message is as follows:

Feb 20 17:24:37 ubuntu python3.8[4164]: Unable to connect to 2001:b28:f23f:f005::a 443
Feb 20 17:24:37 ubuntu python3.8[4164]: Unable to connect to 2001:b28:f23f:f005::a 443
Feb 20 17:24:37 ubuntu python3.8[4164]: Unable to connect to 2001:b28:f23f:f005::a 443
Feb 20 17:24:38 ubuntu python3.8[4164]: Unable to connect to 2001:b28:f23f:f005::a 443
Feb 20 17:24:38 ubuntu python3.8[4164]: Unable to connect to 2001:b28:f23f:f005::a 443
Feb 20 17:24:38 ubuntu python3.8[4164]: Unable to connect to 2001:b28:f23f:f005::a 443
Feb 20 17:24:38 ubuntu python3.8[4164]: Unable to connect to 2001:b28:f23f:f005::a 443
Feb 20 17:24:40 ubuntu python3.8[4164]: Unable to connect to 2001:b28:f23f:f005::a 443
Feb 20 17:24:40 ubuntu python3.8[4164]: Unable to connect to 2001:b28:f23f:f005::a 443
Feb 20 17:24:40 ubuntu python3.8[4164]: Unable to connect to 2001:b28:f23f:f005::a 443

In the latest version, it seems that IPv6 is used for linking by default, causing mtproto to fail to link normally.
Is there a solution to this problem?

Thank you.

**Comment by FemalePresident** [comment]
Hi,

I had to delete the judgment about the IPv6 address under mtprotoproxy.py and the mtproto link was normal. I want to know if I can increase the priority of IPv4 and use IPv4 for links by default.
The deleted statement is as follows:

     IPV6_URL1 = "http://v6.ident.me/"
     IPV6_URL2 = "http://ipv6.icanhazip.com/"

     my_ip_info["ipv6"] = get_ip_from_url(IPV6_URL1) or get_ip_from_url(IPV6_URL2)

Can you provide a better solution?
Looking forward to your reply.

Thank you.

**Comment by HirbodBehnam** [comment]
Hello
I'm not sure what is the best which could be done here. It seems that some other people are having the same [issue](https://github.com/alexbers/mtprotoproxy/issues/243). You can maybe try setting `PREFER_IPV6 = False` in `config.py` file.
Plus, I don't really think this is an issue related to script. So I'm closing it and please continue the discussion in the issue I have linked.
If you think that this issue is related to script, tell me to open it.
