### ISSUE TITLE
I can't connect SSH to my Azure VM after setup a MTProto Proxy 

### ISSUE THREAD

**Issue by hieuvts** [HirbodBehnam/MTProtoProxyInstaller#40]
I install MTProto Proxy using Python script method.
After that the proxy worked perfectly. "systemctl status mtprotoproxy" is active and running.
The problem is when I closed my SSH session and connect it again, terminal on local computer said that "ssh: connect to host <ip address> port 22: Connection timed out"

**Comment by HirbodBehnam** [comment]
Hello
This might be because that this script tries to setup a firewall for you. If you don't want to setup the firewall, just answer 'n' to the `Looks like "firewalld" is not installed Do you want to install it?(y/n)`
If this is indeed a firewall problem, I'm afraid you cannot do anything about it unless Azure gives you terminal access from it's control panel or it does have an option to disable firewall.

**Comment by hieuvts** [comment]
Thank you sir!
